# Generated by Django 5.2.3 on 2025-06-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_image'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='courses.subject', verbose_name='Interests'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pedagogic_level',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('university', 'University'), ('personal', 'Personal')], max_length=20, null=True, verbose_name='Pedagogic Level'),
        ),
    ]
